export const States = [
  { uf: 'RO', name: 'Rondônia' },
  { uf: 'AC', name: 'Acre' },
  { uf: 'AM', name: 'Amazonas' },
  { uf: 'RR', name: 'Roraima' },
  { uf: 'PA', name: 'Pará' },
  { uf: 'AP', name: 'Amapá' },
  { uf: 'TO', name: 'Tocantins' },
  { uf: 'MA', name: 'Maranhão' },
  { uf: 'PI', name: 'Piauí' },
  { uf: 'CE', name: 'Ceará' },
  { uf: 'RN', name: 'Rio Grande do Norte' },
  { uf: 'PB', name: 'Paraíba' },
  { uf: 'PE', name: 'Pernambuco' },
  { uf: 'AL', name: 'Alagoas' },
  { uf: 'SE', name: 'Sergipe' },
  { uf: 'BA', name: 'Bahia' },
  { uf: 'MG', name: 'Minas Gerais' },
  { uf: 'ES', name: 'Espírito Santo' },
  { uf: 'RJ', name: 'Rio de Janeiro' },
  { uf: 'SP', name: 'São Paulo' },
  { uf: 'PR', name: 'Paraná' },
  { uf: 'SC', name: 'Santa Catarina' },
  { uf: 'RS', name: 'Rio Grande do Sul' },
  { uf: 'MS', name: 'Mato Grosso do Sul' },
  { uf: 'MT', name: 'Mato Grosso' },
  { uf: 'GO', name: 'Goiás' },
  { uf: 'DF', name: 'Distrito Federal' },
];
